// Organization Service Error Types

const OrganizationErrorTypes = Object.freeze({
  CONFLICT: "CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_DATA: "INVALID_DATA",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  ALREADY_ACTIVE: "ALREADY_ACTIVE",
  ALREADY_INACTIVE: "ALREADY_INACTIVE",
  INVALID_ORG_TYPE: "INVALID_ORG_TYPE",
  CANNOT_MODIFY_SELF: "CANNOT_MODIFY_SELF",
  INTERNAL_SERVICE_ERROR: "INTERNAL_SERVICE_ERROR"
});

const OrganizationUserErrorTypes = Object.freeze({
  CONFLICT: "CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_DATA: "INVALID_DATA",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  ALREADY_ACTIVE: "ALREADY_ACTIVE",
  ALREADY_INACTIVE: "ALREADY_INACTIVE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
  DUPLICATE_ASSIGNMENT: "DUPLICATE_ASSIGNMENT",
  INVALID_ROLE: "INVALID_ROLE",
  INTERNAL_SERVICE_ERROR: "INTERNAL_SERVICE_ERROR"
});

module.exports = {
  OrganizationErrorTypes,
  OrganizationUserErrorTypes
};
