module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    // ========== USER CONTROLLER EVENTS ==========
    BLOCK_USER: "BLOCK_USER",
    UNBLOCK_USER: "UNBLOCK_USER",
    CHECK_AUTH_LOGS: "CHECK_AUTH_LOGS",
    GET_USER_ACTIVE_DEVICES: "GET_USER_ACTIVE_DEVICES",
    PROVIDE_USER_ACCOUNT_DETAILS: "PROVIDE_USER_ACCOUNT_DETAILS",
    GET_TOTAL_REGISTERED_USERS: "GET_TOTAL_REGISTERED_USERS",
    UPDATE_ADMIN_ROLE: "UPDATE_ADMIN_ROLE",
  
    // ========== ADMIN CONTROLLER EVENTS ==========
    CREATE_ADMIN: "CREATE_ADMIN",
    CREATE_MID_ADMIN: "CREATE_MID_ADMIN",
    ACTIVATE_ADMIN: "ACTIVATE_ADMIN",
    DEACTIVATE_ADMIN: "DEACTIVATE_ADMIN",
    ACTIVATE_MID_ADMIN: "ACTIVATE_MID_ADMIN",
    DEACTIVATE_MID_ADMIN: "DEACTIVATE_MID_ADMIN",
    BLOCK_ADMIN: "BLOCK_ADMIN",
    UNBLOCK_ADMIN: "UNBLOCK_ADMIN",
    VIEW_ADMIN_DETAILS: "VIEW_ADMIN_DETAILS",
    VIEW_OWN_ADMIN_DETAILS: "VIEW_OWN_ADMIN_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS",
    UPDATE_MID_ADMIN_DETAILS: "UPDATE_MID_ADMIN_DETAILS",
    UPDATE_OWN_ADMIN_DETAILS: "UPDATE_OWN_ADMIN_DETAILS",
    CHANGE_ADMIN_SUPERVISOR: "CHANGE_ADMIN_SUPERVISOR",
    CHANGE_MID_ADMIN_SUPERVISOR: "CHANGE_MID_ADMIN_SUPERVISOR",
    
    // ========== STATUS REQUEST EVENTS ==========
    CREATE_DEACTIVATION_REQUEST: "CREATE_DEACTIVATION_REQUEST",
    APPROVE_DEACTIVATION_REQUEST: "APPROVE_DEACTIVATION_REQUEST",
    REJECT_DEACTIVATION_REQUEST: "REJECT_DEACTIVATION_REQUEST",
    CREATE_ACTIVATION_REQUEST: "CREATE_ACTIVATION_REQUEST",
    APPROVE_ACTIVATION_REQUEST: "APPROVE_ACTIVATION_REQUEST",
    REJECT_ACTIVATION_REQUEST: "REJECT_ACTIVATION_REQUEST",
    VIEW_ADMIN_REQUEST: "VIEW_ADMIN_REQUEST",
    
    // ========== ACTIVITY TRACKER EVENTS ==========
    VIEW_ADMIN_ACTIVITY_TRACKER: "VIEW_ADMIN_ACTIVITY_TRACKER",
    LIST_ACTIVITY_TRACKER: "LIST_ACTIVITY_TRACKER",
    BLOCK_USER_DEVICE: "BLOCK_USER_DEVICE",
    UNBLOCK_USER_DEVICE: "UNBLOCK_USER_DEVICE",
    VIEW_USER_DETAILS: "VIEW_USER_DETAILS",
    VIEW_DEVICE_DETAILS: "VIEW_DEVICE_DETAILS",
    CREATE_DEVICE: "CREATE_DEVICE",
    UPDATE_DEVICE: "UPDATE_DEVICE",
    
    // ========== DEVICE MANAGEMENT EVENTS ==========
    DEVICE_BLOCKED: "DEVICE_BLOCKED",
    DEVICE_UNBLOCKED: "DEVICE_UNBLOCKED",
    
    // ========== PERMISSION MANAGEMENT EVENTS ==========
    GRANT_SPECIAL_PERMISSION: "GRANT_SPECIAL_PERMISSION",
    BLOCK_PERMISSION: "BLOCK_PERMISSION",
    REVOKE_PERMISSION_OVERRIDE: "REVOKE_PERMISSION_OVERRIDE",
    VIEW_ADMIN_PERMISSIONS: "VIEW_ADMIN_PERMISSIONS",
    VIEW_PERMISSION_OVERRIDE_DETAILS: "VIEW_PERMISSION_OVERRIDE_DETAILS",
    
    // ========== ROLE CHANGE EVENTS ==========
    CREATE_ROLE_CHANGE_REQUEST: "CREATE_ROLE_CHANGE_REQUEST",
    APPROVE_ROLE_CHANGE_REQUEST: "APPROVE_ROLE_CHANGE_REQUEST",
    REJECT_ROLE_CHANGE_REQUEST: "REJECT_ROLE_CHANGE_REQUEST",
    ROLE_CHANGED: "ROLE_CHANGED",
    
    // ========== CLIENT MANAGEMENT EVENTS ==========
    CREATE_CLIENT: "CREATE_CLIENT",
    CONVERT_USER_TO_CLIENT: "CONVERT_USER_TO_CLIENT",
    CLIENT_ONBOARDING_REQUESTED: "CLIENT_ONBOARDING_REQUESTED",
    APPROVE_CLIENT_ONBOARDING: "APPROVE_CLIENT_ONBOARDING",
    REJECT_CLIENT_ONBOARDING: "REJECT_CLIENT_ONBOARDING",
    REVERT_CLIENT: "REVERT_CLIENT",
    VIEW_CLIENT_DETAILS: "VIEW_CLIENT_DETAILS",
    LIST_CLIENTS: "LIST_CLIENTS",
    CREATE_CLIENT_CONVERSION_REQUEST: "CREATE_CLIENT_CONVERSION_REQUEST",

    CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
    UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
    DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
    DISABLE_ORGANIZATION: "DISABLE_ORGANIZATION",
    ENABLE_ORGANIZATION: "ENABLE_ORGANIZATION",
    GET_ORGANIZATION: "GET_ORGANIZATION",
    LIST_ORGANIZATIONS: "LIST_ORGANIZATIONS",

    CREATE_ORGANIZATION_USER: "CREATE_ORGANIZATION_USER",
    UPDATE_ORGANIZATION_USER: "UPDATE_ORGANIZATION_USER",
    DELETE_ORGANIZATION_USER: "DELETE_ORGANIZATION_USER",
    DISABLE_ORGANIZATION_USER: "DISABLE_ORGANIZATION_USER",
    ENABLE_ORGANIZATION_USER: "ENABLE_ORGANIZATION_USER",
    GET_ORGANIZATION_USER: "GET_ORGANIZATION_USER",
    LIST_ORGANIZATION_USERS: "LIST_ORGANIZATION_USERS"
  }),

  SERVICE_TRACKER_EVENTS: Object.freeze({
    // ========== INTERNAL CONTROLLER EVENTS ==========
    DELETE_INACTIVE_USERS: "DELETE_INACTIVE_USERS",
    
    // ========== SYNC EVENTS ==========
    SYNC_USER_DATA: "SYNC_USER_DATA", 
    SYNC_ADMIN_DATA: "SYNC_ADMIN_DATA",
    SYNC_MY_DATA: "SYNC_MY_DATA",
    
    // ========== SYSTEM EVENTS ==========
    CREATE_SUPER_ADMIN: "CREATE_SUPER_ADMIN",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS"
  })
};